name: Publish Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build:check

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: https://npm.pkg.github.com/
          scope: '@thatcompanys/axios'
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build:check
      - run: rm -f .npmrc
      - name: Create .npmrc for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}\
          @thatcompanys:axios=https://npm.pkg.github.com/\
          always-auth=true" > .npmrc
      - run: cat .npmrc
      - run: npm publish --tag latest --scope @thatcompanys/axios
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org/
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build:check
      - run: npm publish --tag latest
      - run: npm publish --tag latest --scope that-axios
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
