name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build:check

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build:check
      - run: rm -f .npmrc
      - name: Create .npmrc for GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}\n@thatcompanys:axios=https://npm.pkg.github.com/\nalways-auth=true" > .npmrc
      - run: npm publish --tag latest --scope @thatcompanys/axios
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org/
          scope: '@thatcompany/axios'
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build:check
      - run: npm publish --tag latest --scope @thatcompany/axios
      - run: npm publish --tag latest --scope that-axios
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
