name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build:check

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: https://npm.pkg.github.com/
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build:check
      - run: pnpm publish:gpr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build:check
      - run: pnpm run publish:npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
